// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOPfMKbNZcRqHbxwW55Rx6Ee6iJydSlWY',
    appId: '1:312022261590:web:3dfd2f2cc519b6c11700f7',
    messagingSenderId: '312022261590',
    projectId: 'pigeon-161212',
    authDomain: 'pigeon-161212.firebaseapp.com',
    storageBucket: 'pigeon-161212.firebasestorage.app',
    measurementId: 'G-0TXLCST25B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOPfMKbNZcRqHbxwW55Rx6Ee6iJydSlWY',
    appId: '1:312022261590:android:3dfd2f2cc519b6c11700f7',
    messagingSenderId: '312022261590',
    projectId: 'pigeon-161212',
    storageBucket: 'pigeon-161212.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOPfMKbNZcRqHbxwW55Rx6Ee6iJydSlWY',
    appId: '1:312022261590:ios:3dfd2f2cc519b6c11700f7',
    messagingSenderId: '312022261590',
    projectId: 'pigeon-161212',
    storageBucket: 'pigeon-161212.firebasestorage.app',
    iosBundleId: 'com.example.pigeonFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOPfMKbNZcRqHbxwW55Rx6Ee6iJydSlWY',
    appId: '1:312022261590:ios:3dfd2f2cc519b6c11700f7',
    messagingSenderId: '312022261590',
    projectId: 'pigeon-161212',
    storageBucket: 'pigeon-161212.firebasestorage.app',
    iosBundleId: 'com.example.pigeonFlutter',
  );
}
